name: Sushant_Pipeline

on: 
  push: 
    branches: 
      - master
      - test 
  pull_request: 
    branches: 
      - master
    types: [closed] 
  
  

  workflow_dispatch:  # Keep this if you want manual runs


jobs:

 #this is an Job 1....
  on-push:
    if: github.event_name == 'push'  # Fix condition
    runs-on: ubuntu-latest
    steps:
      - name: Print hello Radha
        run: echo "hello Radha"


#this is an Job 2 ....
  on-pull_request:
    if: github.event_name == 'pull_request'  # Fix condition
    runs-on: ubuntu-latest
    steps:
      - name: Print hello Sushant
        run: echo "hello Sushant"
       
  on-pull_request-closed:
          if: github.event_name == 'pull_request' && github.event.action == 'closed'  # Fix condition
          runs-on: ubuntu-latest
          steps:
            - name: Print pull request closed
              run: echo "pull request closed .."


        
  workflow-dispatch-job:
     if: github.event_name == 'workflow_dispatch' 
    
     runs-on: ubuntu-latest
     steps:
        - name: Print workflow dispatch 
          run: echo "Workflow has been run"
