name: Hello World Shell Workflow

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your code

      - name: Print Hello World
        run: echo "Hello, World!"  # Print "Hello, World!" to the log
