name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version here

      - name: Install dependencies
        run: npm install  # Or use your preferred package manager

      - name: Run tests
        run: npm test  # Replace with your test script if different

      - name: Build project
        run: npm run build  # Replace with your build command

   
