name: Python CI

# This workflow will run on every push to the 'main' branch
on:
  push:
    branches:
      - main  # You can change this to your branch if needed

jobs:
  run-hello-world:
    runs-on: ubuntu-latest  # GitHub Actions will use an Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Run the hello.py script
      - name: Run Hello World script
        run: |
          python hello.py  # Running the Python script that prints "Hello, World!"
