name: Python CI

# Trigger workflow on push to 'main' branch or pull request to 'main' branch
on:
  push:
    branches:
      - main  # You can replace 'main' with your branch name if different.
  pull_request:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: ubuntu-latest  # You can change this to 'self-hosted' for a self-hosted runner

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can change the Python version here

    # Step 3: Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a 'requirements.txt' file

    # Step 4: Run Python script
    - name: Run Python script
      run: |
        python app.py  # Replace with the path to your Python script
