name: Python CI

# This workflow will run on every push to the 'main' branch or pull requests targeting 'main'
on:
  push:
    branches:
      - main  # Change this to your desired branch name
  pull_request:
    branches:
      - main  # Change this to your desired branch name

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # This specifies the runner environment (Ubuntu)

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python (you can change the version here)
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # You can specify a different version of Python

      # Step 3: Install dependencies (if you have a requirements.txt)
      # If your project has dependencies, add this step.
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # Step 4: Run the Python program (in this case, hello.py)
      - name: Run Python script
        run: |
          python hello.py  # Replace this with the path to your Python script
